import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import Nav from '../components/layout/nav';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={inter.className}>
        <div className='bg-[#F1F1F1] min-h-[100vh] w-full grid grid-cols-5 '>
          <section className='col-span-1 pt-8'>
            <Nav />
          </section>
          <section className='col-span-4 bg-white w-full h-full rounded-tl-3xl p-8'>
            {children}
          </section>
        </div>
      </body>
    </html>
  );
}
